#!/usr/bin/env sh

set -e

if test "$1" == ""
then
    echo "please give this script a .paka file as an argument"
    exit
fi

if test ! "$1"
then
    echo "could not find input file: $1"
fi

make -C minivm
ldc2 -O1 -i -I ./minivm ./minivm/vm/tod.d -of ./bin/pakac
./minivm/minivm ./bins/boot.bc "$1" -o ./bin/boot.bc
./bin/pakac ./bin/boot.bc > ./bin/out.d
ldc2 -betterC -O3 -release $DFLAGS bin/out.d -c -of bin/out.o
clang -flto=full bin/out.o -o bin/out
