name: Builds
on: [push]
jobs:
  linux-opt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make -B CC=cc OPT='-Os -ffast-math -flto -fomit-frame-pointer'
      - uses: actions/upload-artifact@v2
        with:
          name: boot.bc
          path: bin/stage3.bc