name: Builds
on: [push]
jobs:
  linux-ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make -B CC=cc CFLAGS+=-fsanitize=undefined LFLAGS+=-fsanitize=undefined OPT=-g3
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-linux-debug
          path: bin/minivm
      - uses: actions/upload-artifact@v2
        with:
          name: stage3
          path: bin/stage3.bc
  linux-opt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make -B CC=cc CFLAGS+=-flto LFLAGS+=-flto OPT='-Os -ffast-math'
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-linux-opt
          path: bin/minivm
  windows-opt:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: make -B CC=cc OPT=-Os
      - uses: actions/upload-artifact@v2
        with:
          name: minivm-windows-opt
          path: bin/minivm
